# Font #
font_family Monaspace Argon
font_size 13
modify_font cell_height 110%

# Cursor #
cursor_blink_interval 0
cursor_shape block
cursor_text_color #81a1c1

# Other #
shell_integration no-cursor
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 5000
shell fish

wayland_titlebar_color system
macos_titlebar_color system

allow_remote_control yes

include matugen.conf
