[tools]
bat = "latest"
delta = "latest"
fd = "latest"
go = "latest"
jj = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
rg = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
