#!/bin/bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$({ fd . \
  ~/dotfiles  ~/projects/ ~/projects/DECI/ --type d --max-depth 1 \
  # & fd . ~/.dev/aoc --type d --exact-depth 2;
  } | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_running=$(pgrep tmux)


if ! [[ -z $selected_name ]]; then
  tmux new -A -s $selected_name -c $selected
  exit 0
fi
