
-- Session Stuff (Disabled) {{{
-- local get_session_file = function ()
--     local session_dir = vim.fn.expand(vim.fn.stdpath 'state' .. '/sessions/') -- Sessions directory
--     return session_dir .. vim.fn.getcwd():gsub('/', "%%") .. '.vim' -- Session file for current directory
-- end
--
-- vim.api.nvim_create_autocmd('VimEnter', {
--   group = vim.api.nvim_create_augroup('Restore Session', { clear = true }),
--   callback = function()
--     local session = get_session_file()
--     if session and vim.fn.filereadable(session) then -- If the session file exists and is readable
--       vim.cmd('silent! source ' .. vim.fn.fnameescape(session)) -- Load the session file
--       vim.schedule(function()
--         vim.cmd('silent! bufdo edit!') -- Restore highlights
--       end) -- Delayed to run after neovim launches (doesn't work without this)
--     end
--   end,
-- })
--
-- vim.api.nvim_create_autocmd('VimLeavePre', {
--   group = vim.api.nvim_create_augroup('Save Session', { clear = true }),
--   callback = function()
--     local tmp = vim.o.sessionoptions
--     tmp = table.concat({ 'buffers', 'curdir', 'tabpages', 'winsize', 'skiprtp' }, ',')
--     vim.cmd('mks! ' .. vim.fn.fnameescape(get_session_file()))
--     vim.o.sessionoptions = tmp
--   end,
--   nested = true,
-- }) }}}

